# Generated by Django 4.0.4 on 2022-05-26 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_amenities_facilities_houserule_delete_testtypesz_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Amenities',
            new_name='Amenity',
        ),
        migrations.RenameModel(
            old_name='Facilities',
            new_name='Facility',
        ),
        migrations.AlterModelOptions(
            name='amenity',
            options={'verbose_name_plural': 'Amenities'},
        ),
        migrations.AlterModelOptions(
            name='roomtype',
            options={'verbose_name_plural': 'Room Types'},
        ),
    ]
